name: ited_study_app_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.0+1
  flutter_quill: ^10.7.5
  flutter_quill_extensions: ^10.7.5
  flutter_riverpod: ^2.5.1
  gal: ^2.3.0
  go_router: ^14.2.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  riverpod: ^2.5.1
  super_clipboard: ^0.8.22
  youtube_player_flutter: ^9.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
